#!/usr/bin/env python3
"""Allow the local API to write only to configured storage roots."""

from __future__ import annotations

import argparse
import grp
import json
import os
from pathlib import Path
import pwd
import sys
from typing import Mapping


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--storage-roots", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--pipeline-output", type=Path)
    parser.add_argument("--pipeline-user")
    return parser.parse_args()


def systemd_path(value: Path) -> str:
    text = str(value)
    if not value.is_absolute() or any(character in text for character in "\r\n\x00"):
        raise ValueError("A systemd path must be absolute and contain no control characters")
    safe = b"/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.:-"
    escaped = []
    for byte in text.encode("utf-8"):
        if byte == ord("%"):
            escaped.append("%%")
        elif byte in safe:
            escaped.append(chr(byte))
        else:
            escaped.append(f"\\x{byte:02x}")
    return "".join(escaped)


def configured_paths(value: object) -> list[Path]:
    if not isinstance(value, Mapping):
        raise ValueError("Storage roots configuration must contain an object")

    paths: list[Path] = []
    for root_id, entry in value.items():
        if not isinstance(root_id, str) or not isinstance(entry, Mapping):
            raise ValueError("Storage root entries must contain objects")
        path_value = entry.get("path")
        if not isinstance(path_value, str) or not path_value.strip():
            raise ValueError(f"Storage root {root_id!r} needs a path")
        path = Path(path_value).expanduser().resolve()
        if not path.is_absolute() or path == Path("/"):
            raise ValueError(f"Storage root {root_id!r} is unsafe")
        paths.append(path)

    return sorted(set(paths), key=lambda path: str(path))


def render_override(paths: list[Path]) -> str:
    rows = [
        "# Generated by Jetson Controller; rerun install.sh after changing storage roots.",
        "[Service]",
    ]
    for path in paths:
        # The leading '-' keeps the API available if an external volume is absent.
        rows.append(f"ReadWritePaths=-{systemd_path(path)}")
    rows.append("")
    return "\n".join(rows)


def preferred_results_root(value: object) -> Path:
    if not isinstance(value, Mapping) or not value:
        raise ValueError("Storage roots configuration must contain an object")
    preferred = value.get("recordings")
    candidates = [preferred] if isinstance(preferred, Mapping) else []
    candidates.extend(entry for entry in value.values() if isinstance(entry, Mapping))
    for entry in candidates:
        path_value = entry.get("path")
        if isinstance(path_value, str) and path_value.strip():
            path = Path(path_value).expanduser().resolve()
            if path.is_absolute() and path != Path("/"):
                return path
    raise ValueError("Storage roots configuration has no safe results root")


def systemd_quote(value: str) -> str:
    if any(character in value for character in "\r\n\x00"):
        raise ValueError("A systemd value contains control characters")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
    return f'"{escaped}"'


def render_pipeline_override(results_root: Path, username: str) -> str:
    try:
        account = pwd.getpwnam(username)
        group_name = grp.getgrgid(account.pw_gid).gr_name
    except KeyError as error:
        raise ValueError(f"Pipeline account does not exist: {username}") from error
    return "\n".join(
        (
            "# Generated by Jetson Controller for convention-based pipeline folders.",
            "[Service]",
            f"User={username}",
            f"Group={group_name}",
            f"Environment={systemd_quote('HOME=' + account.pw_dir)}",
            f"ReadWritePaths=-{systemd_path(results_root)}/%i",
            "",
        )
    )


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    try:
        with temporary.open("x", encoding="utf-8") as output:
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    args = parse_args()
    try:
        with args.storage_roots.open("r", encoding="utf-8") as source:
            value = json.load(source)
        write_atomic(args.output, render_override(configured_paths(value)))
        if (args.pipeline_output is None) != (args.pipeline_user is None):
            raise ValueError("--pipeline-output and --pipeline-user must be used together")
        if args.pipeline_output is not None and args.pipeline_user is not None:
            write_atomic(
                args.pipeline_output,
                render_pipeline_override(
                    preferred_results_root(value),
                    args.pipeline_user,
                ),
            )
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
