import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


SCRIPT = (
    Path(__file__).resolve().parents[1]
    / "scripts"
    / "configure-api-storage-access.py"
)
SPEC = importlib.util.spec_from_file_location("configure_api_storage_access", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
storage_access = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(storage_access)


class ConfigureApiStorageAccessTest(unittest.TestCase):
    def test_renders_each_unique_root_as_a_narrow_writable_path(self) -> None:
        paths = storage_access.configured_paths(
            {
                "recordings": {"path": "/data/collections"},
                "duplicate": {"path": "/data/collections/../collections"},
                "legacy": {"path": "/home/Test Path/100%/한글"},
            }
        )

        self.assertEqual(
            storage_access.render_override(paths),
            "# Generated by Jetson Controller; rerun install.sh after changing storage roots.\n"
            "[Service]\n"
            "ReadWritePaths=-/data/collections\n"
            "ReadWritePaths=-/home/Test\\x20Path/100%%/\\xed\\x95\\x9c\\xea\\xb8\\x80\n",
        )

    def test_rejects_filesystem_root_and_invalid_entries(self) -> None:
        with self.assertRaisesRegex(ValueError, "unsafe"):
            storage_access.configured_paths({"all": {"path": "/"}})
        with self.assertRaisesRegex(ValueError, "needs a path"):
            storage_access.configured_paths({"missing": {}})

    def test_cli_writes_override_atomically(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            base = Path(temporary)
            config = base / "storage.json"
            output = base / "unit.d" / "storage-roots.conf"
            config.write_text(
                json.dumps({"recordings": {"path": "/data/collections"}}),
                encoding="utf-8",
            )

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--storage-roots",
                    str(config),
                    "--output",
                    str(output),
                ],
                check=False,
                capture_output=True,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("ReadWritePaths=-/data/collections", output.read_text())
            self.assertEqual(output.stat().st_mode & 0o777, 0o644)


if __name__ == "__main__":
    unittest.main()
