#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -ne 1 ]]; then
  echo "Usage: $0 <public-domain>" >&2
  exit 2
fi
domain="$1"
if [[ ! "${domain}" =~ ^[A-Za-z0-9][A-Za-z0-9.-]{0,252}[A-Za-z0-9]$ ]]; then
  echo "Invalid public domain: ${domain}" >&2
  exit 2
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
app_root="$(cd "${script_dir}/.." && pwd)"
config_root="${XDG_CONFIG_HOME:-${HOME}/.config}/jetson-upload-receiver"
receiver_environment="${config_root}/environment"
if [[ ! -r "${receiver_environment}" ]]; then
  echo "Install the upload receiver before configuring HTTPS" >&2
  exit 1
fi
set -a
# This file is generated by install-user-service.sh and is mode 0600.
source "${receiver_environment}"
set +a
data_root="${UPLOAD_RECEIVER_DATA_ROOT:-/data/server_storage/jetson-upload-receiver}"
expected_mount="${UPLOAD_RECEIVER_EXPECTED_MOUNT:-/data/server_storage}"
if ! mountpoint --quiet "${expected_mount}"; then
  echo "Required HDD is not mounted: ${expected_mount}" >&2
  exit 1
fi
if ! systemctl --user is-active --quiet jetson-upload-receiver.service; then
  echo "Start jetson-upload-receiver.service before configuring HTTPS" >&2
  exit 1
fi

"${app_root}/.venv/bin/pip" install \
  --disable-pip-version-check \
  --requirement "${app_root}/requirements.txt"
"${app_root}/.venv/bin/python" \
  "${app_root}/scripts/ensure-port-forward.py" \
  --expected-domain "${domain}"

install -d -m 0700 "${data_root}/caddy/data" "${data_root}/caddy/config"
unit_root="${XDG_CONFIG_HOME:-${HOME}/.config}/systemd/user"
install -d -m 0700 "${config_root}"
install -d -m 0755 "${unit_root}"

public_environment="${config_root}/public-environment"
temporary_environment="${public_environment}.tmp"
printf '%s\n' \
  "UPLOAD_RECEIVER_DOMAIN=${domain}" \
  "UPLOAD_RECEIVER_DATA_ROOT=${data_root}" \
  "UPLOAD_RECEIVER_UID=$(id -u)" \
  "UPLOAD_RECEIVER_GID=$(id -g)" \
  > "${temporary_environment}"
chmod 0600 "${temporary_environment}"
mv "${temporary_environment}" "${public_environment}"

escape_sed_replacement() {
  printf '%s' "$1" | sed -e 's/[\\&|]/\\&/g'
}
escaped_app_root="$(escape_sed_replacement "${app_root}")"
escaped_environment="$(escape_sed_replacement "${public_environment}")"
escaped_data_root="$(escape_sed_replacement "${data_root}")"

for name in jetson-upload-caddy.service jetson-upload-port-forward.service; do
  temporary_unit="${unit_root}/.${name}.tmp"
  sed \
    -e "s|@APP_ROOT@|${escaped_app_root}|g" \
    -e "s|@PUBLIC_ENV_FILE@|${escaped_environment}|g" \
    -e "s|@DATA_ROOT@|${escaped_data_root}|g" \
    "${app_root}/systemd/${name}" > "${temporary_unit}"
  chmod 0644 "${temporary_unit}"
  mv "${temporary_unit}" "${unit_root}/${name}"
done
install -m 0644 \
  "${app_root}/systemd/jetson-upload-port-forward.timer" \
  "${unit_root}/jetson-upload-port-forward.timer"

systemctl --user daemon-reload
systemctl --user enable --now \
  jetson-upload-caddy.service \
  jetson-upload-port-forward.timer
systemctl --user restart \
  jetson-upload-caddy.service \
  jetson-upload-port-forward.timer

for _attempt in $(seq 1 90); do
  if curl --fail --silent \
    --connect-timeout 5 \
    "https://${domain}/health/ready" >/dev/null; then
    break
  fi
  sleep 2
done
curl --fail --silent --show-error \
  --connect-timeout 5 \
  "https://${domain}/health/ready" >/dev/null

echo "Public receiver configured: https://${domain}"
